receivers:
  profiling:
    BpfVerifierLogLevel: 1
    Tracers: "all"
    SamplesPerSecond: 20
    VerboseMode: true
    SendErrorFrames: false
    OffCPUThreshold: 0

exporters:
  customprofilesexporter:
    export_resource_attributes: true
    export_profile_attributes: true
    export_sample_attributes: true
    export_stack_frames: true
#   export_stack_frame_types:
#     - native
#     - kernel
#     - go
#     - jvm
#     - php
#     - cpython

service:
  pipelines:
    profiles:
      receivers:
        - profiling
      exporters:
        - customprofilesexporter
