receivers:
  profiling:
    BpfVerifierLogLevel: 1
    Tracers: "all"
    SamplesPerSecond: 20
    VerboseMode: true
    SendErrorFrames: false
    OffCPUThreshold: 0

exporters:
  debug:
    verbosity: normal
  customprofilesexporter:
    export_sample_attributes: true
#   export_unwind_types:
#     - native
#     - kernel
#     - go
#     - jvm
#     - php
#     - cpython

service:
  pipelines:
    profiles:
      receivers:
        - profiling
      exporters:
        - debug
        - customprofilesexporter
