receivers:
  profiling:
    Tracers: "all"
    SamplesPerSecond: 20
    BpfVerifierLogLevel: 1
    VerboseMode: true
    SendErrorFrames: false
    OffCPUThreshold: 0
  customprofilesreceiver:
    foo: "bar"
    report_interval: 5s

processors:
  customprofilesprocessor:
    foo: "bar"

exporters:
  customprofilesexporter:
    export_resource_attributes: true
    export_profile_attributes: true
    export_sample_attributes: true
    export_stack_frames: true
    export_stack_frame_types:
      - native
      - kernel
      - go
      - jvm
      - php
      - cpython

service:
  pipelines:
    profiles:
      receivers:
        - profiling
        - customprofilesreceiver
      processors:
        - customprofilesprocessor
      exporters:
        - customprofilesexporter
