receivers:
  profiling:
    tracers: "all"
    samples_per_second: 19
    bpf_verifier_log_level: 1
    verbose_mode: true
    send_error_frames: false
    off_cpu_threshold: 0
    load_probe: true
  customprofilesreceiver:
    foo: "bar"
    report_interval: 5s

processors:
  customprofilesprocessor:
    foo: "bar"

exporters:
  customprofilesexporter:
    export_resource_attributes: true
    export_profile_attributes: true
    export_sample_attributes: true
    export_stack_frames: true
    export_stack_frame_types:
      - native
      - kernel
      - go
      - jvm
      - php
      - cpython
    export_sample_types:
      - samples
      - events

service:
  pipelines:
    profiles:
      receivers:
        - profiling
        - customprofilesreceiver
      processors:
        - customprofilesprocessor
      exporters:
        - customprofilesexporter
