// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package profilingextensionreceiver

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadExtension returns the embedded CollectionSpec for extension.
func loadExtension() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ExtensionBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load extension: %w", err)
	}

	return spec, err
}

// loadExtensionObjects loads extension and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*extensionObjects
//	*extensionPrograms
//	*extensionMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadExtensionObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadExtension()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// extensionSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type extensionSpecs struct {
	extensionProgramSpecs
	extensionMapSpecs
	extensionVariableSpecs
}

// extensionProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type extensionProgramSpecs struct {
	CollectSt *ebpf.ProgramSpec `ebpf:"collect_st"`
}

// extensionMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type extensionMapSpecs struct {
	ProfilerProgs *ebpf.MapSpec `ebpf:"profiler_progs"`
}

// extensionVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type extensionVariableSpecs struct {
}

// extensionObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadExtensionObjects or ebpf.CollectionSpec.LoadAndAssign.
type extensionObjects struct {
	extensionPrograms
	extensionMaps
	extensionVariables
}

func (o *extensionObjects) Close() error {
	return _ExtensionClose(
		&o.extensionPrograms,
		&o.extensionMaps,
	)
}

// extensionMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadExtensionObjects or ebpf.CollectionSpec.LoadAndAssign.
type extensionMaps struct {
	ProfilerProgs *ebpf.Map `ebpf:"profiler_progs"`
}

func (m *extensionMaps) Close() error {
	return _ExtensionClose(
		m.ProfilerProgs,
	)
}

// extensionVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadExtensionObjects or ebpf.CollectionSpec.LoadAndAssign.
type extensionVariables struct {
}

// extensionPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadExtensionObjects or ebpf.CollectionSpec.LoadAndAssign.
type extensionPrograms struct {
	CollectSt *ebpf.Program `ebpf:"collect_st"`
}

func (p *extensionPrograms) Close() error {
	return _ExtensionClose(
		p.CollectSt,
	)
}

func _ExtensionClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed extension_bpfel.o
var _ExtensionBytes []byte
