receivers:
  profiling:
    BpfVerifierLogLevel: 1
    Tracers: php
    SamplesPerSecond: 19
    VerboseMode: true
    SendErrorFrames: false
    OffCPUThreshold: 0

exporters:
  debug:
    verbosity: normal
  customprofilesexporter:
    foo: "baz"
    export_sample_attributes: true
#   export_unwind_types:
#     - native
#     - kernel
#     - go
#     - jvm

  otlp/profiles:
    endpoint: "http://pyroscope:4040"
    tls:
      insecure: true

service:
  pipelines:
    profiles:
      receivers:
        - profiling
      exporters:
        - debug
        - customprofilesexporter
        - otlp/profiles
