receivers:
  profiling:
    tracers: php
    samples_per_second: 19
    verbose_mode: true
    send_error_frames: false

exporters:
  customprofilesexporter:
    export_resource_attributes: true
    export_profile_attributes: true
    export_sample_attributes: true
    export_stack_frames: true
#   export_stack_frame_types:
#     - native
#     - kernel
#     - go
#     - jvm
#     - php
#     - cpython

  otlp/profiles:
    endpoint: "http://pyroscope:4040"
    tls:
      insecure: true

service:
  pipelines:
    profiles:
      receivers:
        - profiling
      exporters:
        - customprofilesexporter
        - otlp/profiles
