receivers:
  profiling:
    BpfVerifierLogLevel: 1
    Tracers: php
    SamplesPerSecond: 19
    VerboseMode: true
    SendErrorFrames: false
    OffCPUThreshold: 0

exporters:
  debug:
    verbosity: normal
  otlp/profiles:
    endpoint: "http://pyroscope:4040"
    tls:
      insecure: true

service:
  pipelines:
    profiles:
      receivers:
        - profiling
      exporters:
        - debug
        - otlp/profiles
