---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-agent
  namespace: node-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-agent-watch-workloads
rules:
  - apiGroups: [ "" ]
    resources: [ "pods", "namespaces" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "apps"]
    resources: [ "replicasets", "deployments"]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-agent-can-watch-workloads
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-agent-watch-workloads
subjects:
  - kind: ServiceAccount
    name: node-agent
    namespace: node-agent
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collector-ebpf-profiler
  namespace: node-agent
spec:
  selector:
    matchLabels:
      name: collector-ebpf-profiler
  template:
    metadata:
      labels:
        name: collector-ebpf-profiler
    spec:
      serviceAccountName: node-agent
      hostPID: true
      containers:
        - name: profiler
          # image: docker.io/danielpacak/opentelemetry-collector-ebpf-profiler:latest
          # imagePullPolicy: IfNotPresent
          image: docker.io/danielpacak/opentelemetry-collector-ebpf-profiler:v0.137.0
          imagePullPolicy: Always
          args:
            - --config=/etc/collector/config.yaml
            - --feature-gates=service.profilesSupport
          env:
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
          ports:
            - containerPort: 1777
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
            - name: config
              mountPath: /etc/collector
            - name: debugfs
              mountPath: /sys/kernel/debug
              readOnly: true
            - name: cgroupfs
              mountPath: /sys/fs/cgroup
              readOnly: true
            - name: procfs
              mountPath: /proc
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: collector
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
        - name: cgroupfs
          hostPath:
            path: /sys/fs/cgroup
        - name: procfs
          hostPath:
            path: /proc
